apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-empleados-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-empleados
      tier: microservicio
  template:
    metadata:
      labels:
        app: ms-empleados
        tier: microservicio
    spec:
      containers:
      - name: ms-empleados-image
        image: ibracoder/ms-empleados:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080