apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-seguros-adm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-seguros-adm
      tier: microservicio
  template:
    metadata:
      labels:
        app: ms-seguros-adm
        tier: microservicio
    spec:
      containers:
      - name: ms-seguros-adm-image
        image: ibracoder/api-seguros-guadalupe-administracion-k8s:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080