apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-seguros-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-seguros
      tier: microservicio
  template:
    metadata:
      labels:
        app: ms-seguros
        tier: microservicio
    spec:
      containers:
      - name: ms-seguros-image
        image: ibracoder/api-seguros-guadalupe-k8s:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080