apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-creditos
  labels:
    app: servicio-creditos
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: servicio-creditos
  template:
    metadata:
      labels:
        app: servicio-creditos
    spec:
      containers:
        - name: servicio-creditos
          image: ibracoder/servicio-creditos-hpa:0.0.1-snapshot
          ports:
            - containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
          resources:
          #solicitud de memoria
            requests:
              memory: "500Mi"
              cpu: "350m"
          #limite de memoria
            limits:
              memory: "1024Mi"
              cpu: "500m"   
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: servicio-creditos
spec:
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: servicio-creditos