apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc-claim-eventual
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-db-pv-eventual