apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv-eventual
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/postgresql/data/postgres"