apiVersion: apps/v1
kind: Deployment
metadata:
  name: holamundo
  labels:
    app: holamundo
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: holamundo
  template:
    metadata:
      labels:
        app: holamundo
    spec:
      containers:
        - name: holamundo
          image: ibracoder/server-app:0.1
          ports:
            - containerPort: 5000
            