apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-seguros-adm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-seguros-adm-deploy
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
