apiVersion: v1
kind: Service
metadata:
  name: ms-seguros-adm-event-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  selector:
    app: ms-seguros-adm-event
    tier: microservicio