apiVersion: v1
kind: Service
metadata:
  name: servicio-cliente
  labels:
    app: servicio-cliente
spec:
  spec:
  type: LoadBalancer
  ports:
  - port: 8081
    name: http
  selector:
    app: servicio-cliente
