apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-clientes-http-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ms-clientes-http
      tier: microservicio
  template:
    metadata:
      labels:
        app: ms-clientes-http
        tier: microservicio
    spec:
      containers:
      - name: ms-clientes-http-image
        image: ibracoder/api-clientes-http:0.0.1-snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080